[package]
name = "numeros_pares"
version = "0.1.0"
authors = ["Epifanio Suárez Martínez"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
